apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: hetzner-microk8s-demo
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    region: nbg1
  controlPlaneRegions:
  - nbg1
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
  - name: control-plane
    type: spread
  - name: md-0
    type: spread
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
    name: hetzner
  sshKeys:
    hcloud:
    - name: lraus-cka_sshkey
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-microk8s-demo-control-plane
  namespace: default
spec:
  template:
    spec:
      imageName: microk8s-ubuntu-22.04-2023-07-21-1830
      placementGroupName: control-plane
      type: cpx31
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-microk8s-demo-md-0
  namespace: default
spec:
  template:
    spec:
      imageName: microk8s-ubuntu-22.04-2023-07-21-1830
      placementGroupName: md-0
      type: cpx31
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hetzner-microk8s-demo
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: MicroK8sControlPlane
    name: hetzner-microk8s-demo-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: hetzner-microk8s-demo
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: hetzner-microk8s-demo-md-0
  namespace: default
spec:
  template:
    spec:
      clusterConfiguration:
        portCompatibilityRemap: true
      initConfiguration:
        confinement: classic
        riskLevel: edge
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: hetzner-microk8s-demo-control-plane
  namespace: default
spec:
  controlPlaneConfig:
    clusterConfiguration:
      portCompatibilityRemap: true
    initConfiguration:
      IPinIP: true
      addons:
      - dns
      - ingress
      confinement: classic
      joinTokenTTLInSecs: 9000
      riskLevel: edge
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HCloudMachineTemplate
      name: hetzner-microk8s-demo-control-plane
  replicas: 1
  upgradeStrategy: SmartUpgrade
  version: v1.25.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: hetzner-microk8s-demo-md-0
  namespace: default
spec:
  clusterName: hetzner-microk8s-demo
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: hetzner-microk8s-demo-md-0
      clusterName: hetzner-microk8s-demo
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: hetzner-microk8s-demo-md-0
      version: 1.25.0
