apiVersion: v1
kind: Namespace
metadata:
  name: ${CABPR_NAMESPACE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CABPR_NAMESPACE}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    region: ${HCLOUD_REGION}
  controlPlaneRegions:
    - ${HCLOUD_REGION}
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: md-0
      type: spread
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
    name: hetzner
  sshKeys:
    hcloud:
      - name: ${HCLOUD_SSH_KEY}

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  namespace: ${CABPR_NAMESPACE}
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.45.0.0/16
    services:
      cidrBlocks:
        - 10.46.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: ${CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: ${CLUSTER_NAME}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${CABPR_NAMESPACE}
spec:
  replicas: ${CABPR_CP_REPLICAS}
  nodeDrainTimeout: 2m
  preRKE2Commands:
    - sleep 30 #fix to give OS time to become ready
  version: ${RKE2_VERSION}
  registrationMethod: internal-first
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
  serverConfig:
    cni: cilium
  agentConfig:
    kubelet:
      extraArgs:
        - "--cloud-provider=external"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudMachineTemplate
    name: ${CLUSTER_NAME}-control-plane
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: ${CLUSTER_NAME}-agent
  name: ${CLUSTER_NAME}-agent
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${CABPR_WK_REPLICAS}
  selector:
    matchLabels:
      nodepool: ${CLUSTER_NAME}-agent
  template:
    metadata:
      labels:
        nodepool: ${CLUSTER_NAME}-agent
    spec:
      version: ${RKE2_VERSION}
      clusterName: ${CLUSTER_NAME}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: RKE2ConfigTemplate
          name: ${CLUSTER_NAME}-agent
          namespace: ${CABPR_NAMESPACE}
      failureDomain: nbg1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: ${CLUSTER_NAME}-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  namespace: ${CABPR_NAMESPACE}
  name: ${CLUSTER_NAME}-agent
spec:
  template:
    spec:
      preRKE2Commands:
        - sleep 30 # fix to give OS time to become ready
      agentConfig:
        kubelet:
          extraArgs:
            - "--cloud-provider=external"
# HCLOUD Maschines
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: control-plane
      type: cpx31
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: default
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: md-0
      type: cpx31
